- hosts: all

  post_tasks:
    - name: Find tarballs and wheels in dist folder.
      find:
        file_type: file
        paths: "{{ ansible_user_dir }}/src/{{ zuul.project.canonical_name }}/dist"
        patterns: "*.tar.gz,*.whl"
      register: result

    - name: Display stat for tarballs and wheels.
      stat:
        path: "{{ item.path }}"
      with_items: "{{ result.files }}"

    - name: Ensure artifacts directory exists.
      file:
        path: "{{ zuul.executor.work_root }}/artifacts"
        state: directory
      delegate_to: localhost

    - name: Collect tarball artifacts.
      fetch:
        dest: "{{ zuul.executor.work_root }}/artifacts/"
        src: "{{ zj_tb.path }}"
        flat: true
      loop: "{{ result.files }}"
      loop_control:
        loop_var: zj_tb

- hosts: localhost
  vars:
    vault_token_dest: "{{ ansible_user_dir }}/.approle-token"
  tasks:
    - name: Fetch gpg key from vault
      no_log: true
      vault_read:
        vault_addr: "{{ vault_addr }}"
        vault_token: "{{ lookup('file', vault_token_dest) }}"
        secret_path: "{{ secret_path_gpg }}"
      register: gpg_secret
      when: zuul_success | bool

    - name: Sign artifacts
      no_log: true
      vars:
        gpg_key:
          private: "{{ gpg_secret.secret.private_key }}"
      include_role:
        name: sign-artifacts
