- hosts: localhost
  tasks:
    - name: Check execution context
      when: "zuul.branch is not defined"
      fail:
        msg: "This playbook must be run in a branch-based pipeline (e.g., 'promote')."

    - name: Download docs archive
      include_role:
        name: download-artifact
      vars:
        # download_artifact_job provided by zuul job
        download_artifact_api: "https://zuul.otc-service.com/api/tenant/{{ zuul.tenant }}"
        download_artifact_type:
          - docs_archive
          - docs_pdf
        download_artifact_pipeline: gate
