- hosts: localhost
  roles:
    - role: ensure-twine
      when: zuul_success | bool

- hosts: localhost
  tasks:
    - name: Fetch pypi credentials from vault
      no_log: true
      vault_read:
        vault_addr: "{{ zuul_project_config_vault.vault_addr }}"
        role_id: "{{ zuul_project_config_vault.role_id }}"
        secret_id: "{{ zuul_project_config_vault.secret_id }}"
        secret_name: "{{ secret_name }}"
      register: secret
      when: zuul_success | bool

    - name: Invoke upload-pypi role
      no_log: true
      include_role:
        name: upload-pypi
      vars:
        pypi_path: "{{ zuul.executor.work_root }}/artifacts"
        pypi_info:
          username: "{{ secret.username }}"
          password: "{{ secret.password }}"
      when: zuul_success | bool
