- hosts: localhost
  roles:
    - role: ensure-twine
      when: zuul_success | bool

- hosts: localhost
  vars:
    vault_token_dest: "{{ ansible_user_dir }}/.approle-token"
  tasks:
    - name: Fetch pypi credentials from vault
      no_log: true
      vault_read:
        vault_addr: "{{ vault_addr }}"
        vault_token: "{{ lookup('file', vault_token_dest) }}"
        secret_path: "{{ secret_path_pypi }}"
      register: pypi_secret
      when: zuul_success | bool

    - name: Invoke upload-pypi role
      no_log: true
      include_role:
        name: upload-pypi
      vars:
        pypi_path: "{{ zuul.executor.work_root }}/artifacts"
        pypi_info:
          username: "{{ pypi_secret.secret.username }}"
          password: "{{ pypi_secret.secret.password }}"
      when: zuul_success | bool
