---
- hosts: all
  vars:
    vault_token_dest: "{{ ansible_user_dir }}/.approle-token"
  tasks:
    - name: Fetch gpg key from vault
      delegate_to: localhost
      no_log: true
      vault_read:
        vault_addr: "{{ vault_addr }}"
        vault_token: "{{ lookup('file', vault_token_dest) }}"
        secret_path: "{{ secret_path_gpg }}"
      register: gpg_secret
      when: zuul_success | bool

    - name: Create GPG private key tempfile
      tempfile:
        state: file
      register: gpg_private_key_tmp

    - name: Create GPG private key
      copy:
        content: "{{ gpg_secret.secret.private_key }}"
        dest: "{{ gpg_private_key_tmp.path }}"
        mode: 0400

    - name: Import GPG private key
      command: "gpg --allow-secret-key-import --import {{ gpg_private_key_tmp.path }}"

    - name: Delete GPG private key
      file:
        path: "{{ gpg_private_key_tmp.path }}"
        state: absent

    - name: Trigger goreleaser
      command: "bin/goreleaser release"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        GITHUB_TOKEN: "{{ goreleaser_github_token.token | default('fake') }}"
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
