---
- hosts: localhost
  vars:
    vault_token_path: "{{ ansible_user_dir }}/.approle-token"
    vault_token: "{{ lookup('file', vault_token_path) }}"
  tasks:
    - name: Fetch gpg key from vault
      no_log: true
      vault_read:
        vault_addr: "{{ vault_addr }}"
        vault_token: "{{ vault_token }}"
        secret_path: "{{ secret_path_gpg }}"
      register: gpg_secret

    - name: Write gpg_secret token into the file
      copy:
        content: "{{ gpg_secret.secret.private_key }}"
        dest: "{{ zuul.executor.work_root }}/.gpg.key"
        mode: "0400"

    - name: Fetch GitHub token
      vars:
        project: "{{ zuul.project.name.split('/') }}"
      no_log: true
      uri:
        url: "{{ vault_addr }}/v1/{{ vault_github_token_path }}"
        headers:
          "X-Vault-Token": "{{ vault_token }}"
        method: "POST"
        body:
          permissions: "contents=write"
          org_name: "{{ project[0] }}"
          repositories: "{{ project[1] }}"
        body_format: "json"
      register: github_token

    - name: Write github key into the file
      copy:
        content: "{{ github_token.json.data.token }}"
        dest: "{{ zuul.executor.work_root }}/.github"
        mode: "0400"

- hosts: all
  vars:
    gpg_key_path: "{{ zuul.executor.work_root }}/.gpg.key"
    github_token_path: "{{ zuul.executor.work_root }}/.github"
  tasks:
    - name: Create GPG private key
      copy:
        src: "{{ gpg_key_path }}"
        dest: "{{ ansible_user_dir }}/.gpg.key"
        mode: "0400"
      register: gpg_key

    - name: Create GitHub token file
      copy:
        src: "{{ zuul.executor.work_root }}/.github_token"
        dest: "{{ ansible_user_dir }}/.github_token"
        mode: "0400"
      register: github_token

    - name: Import GPG private key
      command: "gpg --allow-secret-key-import --import {{ gpg_key.dest }}"

    - name: Delete GPG private key
      file:
        path: "{{ gpg_key.dest }}"
        state: "absent"

    # TODO: Populate env_file (https://goreleaser.com/scm/github/?h=github)
    - name: Trigger goreleaser
      command: "bin/goreleaser release"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        GITHUB_TOKEN: "{{ lookup('file', github_token_path) | default('fake') }}"
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

- hosts: localhost
  vars:
    vault_token_path: "{{ ansible_user_dir }}/.approle-token"
    gpg_key_path: "{{ zuul.executor.work_root }}/.gpg.key"
    github_token_path: "{{ zuul.executor.work_root }}/.github"
  tasks:
    - name: Revoke GitHub token
      uri:
        url: "{{ vault_addr }}/v1/sys/leases/revoke"
        headers:
          "X-Vault-Token": "{{ lookup('file', vault_token_path) }}"
        method: "DELETE"
        data:
          lease_id: "{{ github_token.json.lease_id }}"

    - name: Delete secret files
      file:
        path: "{{ item }}"
        state: "absent"
      loop:
        - "{{ gpg_key_path }}"
        - "{{ github_token_path }}"
