---
- hosts: localhost
  vars:
    vault_token_path: "{{ ansible_user_dir }}/.approle-token"
    vault_token: "{{ lookup('file', vault_token_path) }}"
  tasks:
    - name: Fetch gpg key from vault
      no_log: true
      vault_read:
        vault_addr: "{{ vault_addr }}"
        vault_token: "{{ vault_token }}"
        secret_path: "{{ secret_path_gpg }}"
      register: gpg_secret

    - name: Write gpg_secret token into the file
      copy:
        content: "{{ gpg_secret.secret.private_key }}"
        dest: "{{ ansible_user_dir }}/.gpg.key"
        mode: "0440"

    - name: Fetch GitHub token
      vars:
        project: "{{ zuul.project.name.split('/') }}"
      no_log: true
      uri:
        url: "{{ vault_addr }}/v1/{{ vault_github_token_path }}"
        headers:
          "X-Vault-Token": "{{ vault_token }}"
        method: "POST"
        body:
          permissions: "contents=write"
          org_name: "{{ project[0] }}"
          repositories: "{{ project[1] }}"
        body_format: "json"
      register: github_token

    - name: Write github key into the file
      copy:
        content: "{{ github_token.json.data.token }}"
        dest: "{{ ansible_user_dir }}/.github"
        mode: "0440"

- hosts: all
  vars:
    gpg_key: "{{ hostvars['localhost']['gpg_secret']['secret']['private_key'] }}"
    github_token: "{{ hostvars['localhost']['github_token']['json']['data']['token'] }}"
  tasks:
    - name: Create GPG private key tempfile
      tempfile:
        state: file
      register: gpg_private_key_tmp

    - name: Create GPG private key
      copy:
        content: "{{ gpg_key }}"
        dest: "{{ gpg_private_key_tmp.path }}"
        mode: 0400

    - name: Import GPG private key
      command: "gpg --allow-secret-key-import --import {{ gpg_private_key_tmp.path }}"

    - name: Delete GPG private key
      file:
        path: "{{ gpg_private_key_tmp.path }}"
        state: absent

    - name: Trigger goreleaser
      command: "bin/goreleaser release"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        GITHUB_TOKEN: "{{ github_token | default('fake') }}"
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

- hosts: localhost
  tasks:
    - name: Revoke GitHub token
      uri:
        url: "{{ vault_addr }}/v1/sys/leases/revoke"
        headers:
          "X-Vault-Token": "{{ 'file', vault_token_dest) }}"
        method: "DELETE"
        data:
          lease_id: "{{ github_token.lease_id }}"
