- hosts: all
  tasks:
    - name: Find matching PDF files
      find:
        paths: "{{ zuul.project.src_dir }}/doc/build/pdf"
        patterns: "{{ zuul.project.short_name }}-*.pdf"
      register: pdf_files

    - name: Debug the list of PDF files
      debug:
        var: pdf_files.files

    - name: Fetch sphinx tarball
      include_role:
        name: fetch-sphinx-tarball
      vars:
        sphinx_pdf_files: "{{ pdf_files.files | map(attribute='path') | list }}"
      when: zuul_success | bool

    - name: Fetch archive
      fetch:
        dest: "{{ zuul.executor.work_root }}/"
        src: "{{ ansible_user_dir }}/zuul-output/logs/docs-html.tar.gz"
        flat: "true"
      when: zuul_success | bool
    #TODO: fetch PDF files

    - name: Fetch sphinx json
      include_role:
        name: fetch-sphinx-json
      when: zuul_success | bool

    - name: Fetch json archive
      fetch:
        dest: "{{ zuul.executor.work_root }}/"
        src: "{{ ansible_user_dir }}/zuul-output/logs/docs-json.tar.gz"
        flat: "true"
      when: zuul_success | bool
      failed_when: false
