- hosts: all
  tasks:
    - name: Fetch sphinx tarball
      include_role:
        name: fetch-sphinx-tarball
      when: zuul_success | bool

    - name: Fetch archive
      fetch:
        dest: "{{ zuul.executor.work_root }}/"
        src: "{{ ansible_user_dir }}/zuul-output/logs/docs-html.tar.gz"
        flat: "true"
      when: zuul_success | bool
    #TODO: fetch PDF files

    - name: Fetch sphinx json
      include_role:
        name: fetch-sphinx-json
      when: zuul_success | bool


