- hosts: localhost
  tasks:
    - name: Check execution context
      when: "zuul.branch is not defined"
      fail:
        msg: "This playbook must be run in a branch-based pipeline (e.g., 'promote')."

- hosts: all
  roles:
    - role: ensure-if-python
      # docs do not need the package itself to be installed
      install_package: false
    - role: tox
      tox_envlist: docs
      bindep_profile: compile doc
    - role: build-pdf-docs
      when: not tox_skip_pdf
