- hosts: localhost
  tasks:
    - name: Check execution context
      when: "zuul.branch is not defined"
      fail:
        msg: "This playbook must be run in a branch-based pipeline (e.g., 'promote')."

- hosts: all
  roles:
    - role: ensure-if-python
      # docs do not need the package itself to be installed
      install_package: false
    - role: tox
      tox_envlist: "{{ tox_envlist | default('docs') }}"
      bindep_profile: compile doc
    - role: build-pdf-docs
      when: not tox_skip_pdf
  tasks:
    - block:
        # Build json output, but do not fail
        - name: Execute sphinx to generate JSON output
          include_role:
            name: sphinx
          vars:
            sphinx_builders: json
            zuul_work_virtualenv: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/.tox/{{ tox_envlist }}"
      ignore_errors: yes
